language: ruby
rvm:
  - 2.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgsl0ldbl libgsl0-dev
install: gem install bundler && gem install s3_website && gem install rake && bundle install
script: jekyll build && s3_website push
