# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               graham gilbert dot com
tagline:             'Mac administration and assorted nerdity'
description:         'A Mac admin, automating the hell out of things in London.<br /><br />The opinions on this site are my own, and are not necessarily shared by my employer.'
url:                 http://grahamgilbert.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Graham Gilbert
  url:               http://grahamgilbert.com
  email:             graham@grahamgilbert.com

# Custom vars
version:             1.0.0

gems:
  - octopress-codefence
  - octopress-codeblock
  - octopress-solarized
  - jekyll-sitemap

permalink:   /blog/:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true
excerpt_separator: <!-- more -->
