# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
relative_permalinks: true

# Setup
title:               graham gilbert
tagline:             'assorted nerdity'
description:         'assorted nerdity'
url:                 https://grahamgilbert.com
baseurl:             '/'
paginate:            5
enforce_ssl: grahamgilbert.com
encoding: utf-8

# About/contact
author:
  name:              Graham Gilbert
  url:               https://grahamgilbert.com
  email:             graham@grahamgilbert.com

# Custom vars
version:             1.0.0

gems:
  - octopress-codefence
  - octopress-codeblock
  - octopress-solarized
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: /atom.xml

permalink:   /blog/:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true
excerpt_separator: <!-- more -->
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/