defaults: &defaults
  working_directory: /tmp/blog
  docker:
    - image: grahamgilbert/blog-build@sha256:008eb268fd49391637393ac1811b3f257b0f48ac3048a748fe6032c9b72e06d9
  environment:
    - SOURCE_DIR: /tmp/blog/_site
    - S3_BUCKET: grahamgilbertcom
    - S3_REGION: us-east-1
  
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: jekyll build
          command: bundle exec jekyll build --lsi --source $CIRCLE_WORKING_DIRECTORY
      - persist_to_workspace:
          root: /tmp/blog
          paths:
            - '_site'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/blog
      - run:
          name: run tests
          command: |
            htmlproofer --check-html --alt-ignore '/.*/' $SOURCE_DIR
  deploy:
    <<: *defaults
    docker:
       - image: clburlison/s3deploy@sha256:81c31d3e4a9bc53a6ed17285ed32fcfd05aa0e3cd09469788a20506ff0cc3732
    steps:
      - attach_workspace:
          at: /tmp/blog
      - run:
          name: Upload to s3
          command: /usr/local/bin/s3deploy -source="$SOURCE_DIR" -region="$S3_REGION" -bucket="$S3_BUCKET"
  invalidate:
    <<: *defaults
    docker:
      - image: grahamgilbert/awscli@sha256:cd9851bb4155e89830f33bca28e2da732077ea99abf7fd8115b42d6a4a499967
    steps:
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - invalidate:
            requires:
              - deploy
            filters:
              branches:
                only: master