defaults: &defaults
  working_directory: /src
  docker:
    - image: klakegg/hugo:0.71.1
  environment:
    - SOURCE_DIR: /tmp/blog/public
    - S3_BUCKET: grahamgilbertcom
    - S3_REGION: us-east-1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: hugo
          command: hugo --source $CIRCLE_WORKING_DIRECTORY
      - persist_to_workspace:
          root: /tmp/blog
          paths:
            - "hugo"
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/blog
      - run:
          name: run tests
          command: |
            htmlproofer --check-html --alt-ignore '/.*/' --disable_external $SOURCE_DIR
  deploy:
    <<: *defaults
    docker:
      - image: grahamgilbert/awscli@sha256:f885d8ea981fd0b44d119a3d85c6994274b6cf93b05f6f3a883cc8c656ba3763
    steps:
      - attach_workspace:
          at: /tmp/blog
      - run:
          name: Upload to s3
          command: aws s3 sync $SOURCE_DIR s3://$S3_BUCKET --delete
  invalidate:
    <<: *defaults
    docker:
      - image: grahamgilbert/awscli@sha256:f885d8ea981fd0b44d119a3d85c6994274b6cf93b05f6f3a883cc8c656ba3763
    steps:
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - invalidate:
          requires:
            - deploy
          filters:
            branches:
              only: master
