defaults: &defaults
  working_directory: ~/blog
  
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      # specify the version you desire here
       - image: grahamgilbert/blog-build:latest
    steps:
      - checkout
      - run: bundle exec jekyll build --lsi
      # run tests! Uncomment these later
      # - run:
      #     name: run tests
      #     command: |
      #       htmlproofer --check-html $CIRCLE_WORKING_DIRECTORY/_site
      - persist_to_workspace:
          root: .
          path: .
  deployment:
    <<: *defaults
    docker:
       - image: circleci/python:2-jessie-browsers
    steps:
      - attach_workspace:
          at: ~/blog
      - run: sudo pip install awscli
      - run: aws s3 sync $CIRCLE_WORKING_DIRECTORY/_site s3://grahamgilbertcom/ --dryrun
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: master