defaults: &defaults
  working_directory: /tmp/blog
  environment:
    - SOURCE_DIR: /tmp/blog/_site
    - LANG: en_US.UTF-8
    - LANGUAGE: en_US:en
    - TZ: America/Los_Angeles
    - LC_ALL: en_US.UTF-8
    - LANG: en_US.UTF-8
    - LANGUAGE: en_US
  
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: grahamgilbert/blog-build@sha256:008eb268fd49391637393ac1811b3f257b0f48ac3048a748fe6032c9b72e06d9
    steps:
      - checkout
      - run:
          name: jekyll build
          command: bundle exec jekyll build --lsi --source $CIRCLE_WORKING_DIRECTORY
      # run tests! Uncomment these later
      # - run:
      #     name: run tests
      #     command: |
      #       htmlproofer --check-html $CIRCLE_WORKING_DIRECTORY/_site
      - persist_to_workspace:
          root: /tmp/blog
          paths:
            - '_site'
  deployment:
    <<: *defaults
    docker:
       - image: circleci/python:2-jessie-browsers
    steps:
      - attach_workspace:
          at: /tmp/blog
      - run: sudo pip install awscli
      - run: aws s3 sync $SOURCE_DIR s3://grahamgilbertcom/ --dryrun
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: master